### ISSUE TITLE
Change question "calling-incorrect-partial-correct' mechanic

### ISSUE THREAD

**Issue by AstroDocCarl** [bubba0077/Trivia#228] opened 2016-02-15 00:52 UTC
This was the first year where I did a lot of calling since we have had the client program. I found dealing with the drop down box rather tedious, especially when shot-gunning guesses. I think it would be nice to have buttons instead of the drop down box. Of course this limits the label length of the button to get everthing in there, even just a one letter label would probably be fine  like "C", "W", "P", "R" for calling, wrong, partial, right. Just an idea.

**Comment by bubba0077** [comment] 2019-02-18 10:12
Closed as duplicate of #247

**Closed by bubba0077** 2019-02-18 10:12 UTC
Labels: duplicate, question
